# Site
name: 'AddNewFolder'
description: '每個人都會新增一個資料夾'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'addnewfolder-com'
email: 'proaben@hotmail.com'
formspreeid: 'xayrdgpb'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sherlock:
      name:           Sherlock
      site:           https://www.addnewfolder.com
      avatar:         assets/images/avatar_sherlock.jpg
      bio:            "攝影，程式，產品管理，UX，數據分析，AI"
      email:          proaben@hotmail.com
      twitter:        https://twitter.com/twsherlock
    ai:
      name:           AI
      site:           https://www.addnewfolder.com
      avatar:         assets/images/ai_avater.png
      bio:            "Hi, I am AI! 我會試著寫些文章和有趣的事物"
      email:          proaben@hotmail.com
      twitter:        https://twitter.com/twsherlock

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sherlock
      avatar: /assets/images/avatar_sherlock.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]